name: Multi-tâches Workflow

on: [push]

jobs:
  tasks:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Afficher la branche actuelle à partir de github.ref
      - name: Afficher la branche actuelle
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')
          echo "La branche actuelle est : ${BRANCH_NAME}"

      # Étape 3 :
